### ISSUE TITLE
Comment causes parse error on import after require

### ISSUE THREAD

**Issue by deliciouslytyped** [theam/require#16]
something like the following:
```
require Data.IORef --a comment
```
results in an error on the import after it:
```
path/to/src.hs:3:1: error: parse error on input ‘import’
   |
3  | import Other.Import
   | ^^^^^
```

a more proper test case:
```
module Wat where
require Data.IORef --a comment
import Data.Text
```

**Comment by NickSeagull** [comment]
Thanks for reporting 😄 

Indeed this is a case that has not been taken into account, will try to solve it as soon as possible
