### ISSUE TITLE
Error when using haskell.nix

### ISSUE THREAD

**Issue by deliciouslytyped** [theam/require#23]
How can I fix this?:

```
There is no Requires file in the system
`requirepp' failed in phase `Haskell pre-processor'. (Exit code: 1)
```

The relevant section of my cabal:

```
    require >= 0.4.3
  build-tool-depends:
    require:requirepp >= 0.4.3
```

Without the `build-tool-depends` it failes to execute requirepp, presumably it can't see it.

**Comment by deliciouslytyped** [comment]
Here's the ghcoptions:
```
  ghc-options:
    -threaded -O0
    -Wall -Wno-unused-imports
    -F -pgmF requirepp
```

**Comment by NickSeagull** [comment]
Do you have a `Requires` file? `require` is looking for some `Requires` file in the project root and it is failing to find it.

[This is an example Requires file](https://github.com/theam/require/blob/master/Requires)

**Comment by deliciouslytyped** [comment]
I noticed that before I had to run off. From what little I could find on it on the spur of the moment it looked like something only needed for autorequire or somesuch.

I'll try adding it.

**Comment by deliciouslytyped** [comment]
Where does it expect the file to be?

**Comment by NickSeagull** [comment]
In theory it should be in the project root. Could you share a repo to see if I can reproduce?

**Comment by deliciouslytyped** [comment]
I'm attaching a minimal repro.
Run with `nix-build -v haskell-nix.nix -A repro.components.exes.repro`, you should get something like
```
[snip]
Configure flags:
--prefix=/nix/store/6sribgckan9hxyx0qmmcp895cmpr1n79-repro-0.0-exe-repro exe:repro --package-db=clear --package-db=/nix/store/63wj1k42fba8yjis3krmz6faijbpz7ln-repro-0.0-exe-repro-config/lib/ghc-8.6.5/package.conf.d --exact-configuration --dependency=require=require-0.4.3-Eaf9hkljb94L1us1WxAdaY --dependency=rts=rts --dependency=ghc-heap=ghc-heap-8.6.5 --dependency=ghc-prim=ghc-prim-0.5.3 --dependency=integer-gmp=integer-gmp-1.0.2.0 --dependency=base=base-4.12.0.0 --dependency=deepseq=deepseq-1.4.4.0 --dependency=array=array-0.5.3.0 --dependency=ghc-boot-th=ghc-boot-th-8.6.5 --dependency=pretty=pretty-1.1.3.6 --dependency=template-haskell=template-haskell-2.14.0.0 --dependency=ghc-boot=ghc-boot-8.6.5 --dependency=ghc=ghc-8.6.5 --dependency=Cabal=Cabal-2.4.0.1 --dependency=array=array-0.5.3.0 --dependency=binary=binary-0.8.6.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=containers=containers-0.6.0.1 --dependency=directory=directory-1.3.3.0 --dependency=filepath=filepath-1.4.2.1 --dependency=ghc-boot=ghc-boot-8.6.5 --dependency=ghc-compact=ghc-compact-0.1.0.0 --dependency=ghc-prim=ghc-prim-0.5.3 --dependency=hpc=hpc-0.6.0.3 --dependency=mtl=mtl-2.2.2 --dependency=parsec=parsec-3.1.13.0 --dependency=process=process-1.6.5.0 --dependency=text=text-1.2.3.1 --dependency=time=time-1.8.0.2 --dependency=transformers=transformers-0.5.6.2 --dependency=unix=unix-2.7.2.2 --dependency=xhtml=xhtml-3000.2.2.1 --with-ghc=ghc --with-ghc-pkg=ghc-pkg --with-hsc2hs=hsc2hs --with-gcc=cc --with-ld=ld.gold --ghc-option=-optl-fuse-ld=gold --ld-option=-fuse-ld=gold --with-ar=ar --with-strip=strip --disable-executable-stripping --disable-library-stripping --disable-library-profiling --disable-executable-profiling --enable-static --enable-shared --enable-split-sections
Configuring executable 'repro' for repro-0.0..
Warning: The flag --disable-executable-profiling is deprecated. Please use
--disable-profiling instead.
Warning: 'license: Undecided' is not a recognised license. The known licenses
are: GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, AGPL, AGPL-3, BSD2, BSD3, MIT,
ISC, MPL-2.0, Apache, Apache-2.0, PublicDomain, AllRightsReserved,
OtherLicense
building
Preprocessing executable 'repro' for repro-0.0..
Building executable 'repro' for repro-0.0..
There is no Requires file in the system
`requirepp' failed in phase `Haskell pre-processor'. (Exit code: 1)
builder for '/nix/store/yj1rwvjsx9rh39m7cid9f7wvd0rzka89-repro-0.0-exe-repro.drv' failed with exit code 1
error: build of '/nix/store/yj1rwvjsx9rh39m7cid9f7wvd0rzka89-repro-0.0-exe-repro.drv' failed

```

[reqrepro.zip](https://github.com/theam/require/files/4322892/reqrepro.zip)

**Comment by NickSeagull** [comment]
I cannot seem to be able to reproduce this by building with Cabal-v2 nor Stack. Perhaps Nix is doing something weird with the working directory?

I don't have access to Nix right now. Could you try debugging paths and so, to see if everything is working as expected?

Please paste any insights you might find 🙂

**Comment by deliciouslytyped** [comment]
I assume this indeed has something to do with the nix process. I'll try to look into it more.

**Comment by deliciouslytyped** [comment]
Ok, yeah, this is a "me" problem I think, or at least not a requires problem.
My hypothesis is https://github.com/input-output-hk/haskell.nix/blob/98ac006e995d310c9329787bd93f6c3384174713/lib/call-cabal-project-to-nix.nix#L44 is using a cleaned subset of the input files where they only accept some extensions in the top level directory; https://github.com/input-output-hk/haskell.nix/blob/98ac006e995d310c9329787bd93f6c3384174713/lib/call-cabal-project-to-nix.nix#L36
so the Requires file is getting removed.

If I don't use autorequires however, why is Requires mandatory?

**Comment by NickSeagull** [comment]
Yep, that's definitely a bug, somehow the loading of the Requires file got duplicated and ended up in [`the require Main`](https://github.com/theam/require/blob/master/library/Require.hs#L34) would you be up to submit a patch removing the loading part?

**Comment by deliciouslytyped** [comment]
Could you do it? I'm not really comfortable with haskell (yet).

**Comment by NickSeagull** [comment]
This should be fixed in #24 , check the changes :)

Feel free to reopen if the issue persists. Note that probably this won't be added to Stackage/Hackage soon, so you might need to add the `master` branch of this repo as an extra package

**Comment by deliciouslytyped** [comment]
nitpick: Doesn't hackage already have a 0.4.3?

**Comment by NickSeagull** [comment]
Yes, just bumped to 0.4.4.

**Comment by deliciouslytyped** [comment]
Yep, that worked.
I just added 

```
source-repository-package
  type:git
  location:https://github.com/theam/require.git
  tag:ae53ebb9f133578f0e91892ded2886d5ecc27c69
  --sha256:09dil57c04xl0briklsr15gyijnrdx3258j4l3rv0v825iq5df8y
```
to cabal.project to get it to work. (the sha256 is haskell.nix stuff).

I'm still looking at the file fitering issue because it's bothering me and I'll need to fix it if I do end up wanting autoimport.

**Comment by NickSeagull** [comment]
Awesome, thanks for helping in solving this issue! 😄
